// Itinerary PDF Generation
// Phase 2.4 - Nightclub Booking System

import { jsPDF } from 'jspdf';

export interface ItineraryEvent {
  id: string;
  name: string;
  date: string;
  door_time: string | null;
  venue: {
    name: string;
    address: string;
  };
}

export interface ItineraryPerformance {
  id: string;
  artist: {
    name: string;
    city: string | null;
    contact_email: string | null;
  };
  start_time: string;
  end_time: string;
  stage: string;
}

export interface ItineraryItem {
  performance_id: string;
  arrival_time: string | null;
  hotel: string | null;
  notes: string | null;
}

export interface ItineraryData {
  event: ItineraryEvent;
  performances: Array<ItineraryPerformance & { itinerary?: ItineraryItem }>;
}

export interface FormattedItinerary {
  eventName: string;
  eventDate: string;
  venueName: string;
  venueAddress: string;
  performances: Array<{
    artistName: string;
    startTime: string;
    endTime: string;
    stage: string;
    arrivalTime?: string | null;
    hotel?: string | null;
    notes?: string | null;
  }>;
}

/**
 * Formats itinerary data for PDF generation
 */
export function formatItineraryData(data: ItineraryData): FormattedItinerary {
  return {
    eventName: data.event.name,
    eventDate: data.event.date,
    venueName: data.event.venue.name,
    venueAddress: data.event.venue.address,
    performances: data.performances.map((p) => ({
      artistName: p.artist.name,
      startTime: p.start_time,
      endTime: p.end_time,
      stage: p.stage,
      arrivalTime: p.itinerary?.arrival_time ?? null,
      hotel: p.itinerary?.hotel ?? null,
      notes: p.itinerary?.notes ?? null,
    })),
  };
}

/**
 * Generates a PDF itinerary document
 */
export function generateItineraryPDF(data: ItineraryData): jsPDF {
  const doc = new jsPDF();
  const formatted = formatItineraryData(data);
  
  // Dark theme colors
  const darkBg = [26, 26, 26] as [number, number, number];
  const accentColor = [139, 92, 246] as [number, number, number];
  const textColor = [255, 255, 255] as [number, number, number];
  const lightText = [156, 163, 175] as [number, number, number];

  // Header
  doc.setFillColor(...darkBg);
  doc.rect(0, 0, 210, 297, 'F');
  
  doc.setTextColor(...accentColor);
  doc.setFontSize(24);
  doc.text(formatted.eventName, 15, 25);
  
  doc.setTextColor(...textColor);
  doc.setFontSize(14);
  doc.text(`Date: ${formatted.eventDate}`, 15, 35);
  doc.text(`Venue: ${formatted.venueName}`, 15, 42);
  doc.text(formatted.venueAddress, 15, 49);

  // Running Order Header
  doc.setDrawColor(...accentColor);
  doc.line(15, 58, 195, 58);
  
  doc.setTextColor(...accentColor);
  doc.setFontSize(16);
  doc.text('Running Order', 15, 68);

  // Performances
  let yPosition = 82;
  doc.setFontSize(11);
  
  formatted.performances.forEach((perf, index) => {
    // Check if we need a new page
    if (yPosition > 260) {
      doc.addPage();
      doc.setFillColor(...darkBg);
      doc.rect(0, 0, 210, 297, 'F');
      yPosition = 20;
    }

    // Artist name and time
    doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    doc.setFontSize(12);
    doc.text(`${index + 1}. ${perf.artistName}`, 15, yPosition);
    
    doc.setTextColor(lightText[0], lightText[1], lightText[2]);
    doc.setFontSize(10);
    doc.text(`${perf.startTime} - ${perf.endTime} | ${perf.stage}`, 15, yPosition + 6);
    
    // Itinerary details (if available)
    yPosition += 14;
    
    if (perf.arrivalTime || perf.hotel || perf.notes) {
      if (perf.arrivalTime) {
        doc.setTextColor(139, 92, 246);
        doc.text(`Arrival: ${perf.arrivalTime}`, 20, yPosition);
        yPosition += 5;
      }
      if (perf.hotel) {
        doc.setTextColor(156, 163, 175);
        doc.text(`Hotel: ${perf.hotel}`, 20, yPosition);
        yPosition += 5;
      }
      if (perf.notes) {
        doc.setTextColor(156, 163, 175);
        doc.text(`Notes: ${perf.notes}`, 20, yPosition);
        yPosition += 5;
      }
      yPosition += 5;
    }
  });

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(107, 114, 128);
    doc.text(
      `${formatted.eventName} - Itinerary | Page ${i} of ${totalPages}`,
      15,
      285
    );
    doc.text('Generated by PAL Nightclub Booking System', 15, 290);
  }

  return doc;
}

/**
 * Downloads the itinerary PDF
 */
export function downloadItineraryPDF(data: ItineraryData): void {
  const doc = generateItineraryPDF(data);
  const fileName = `${data.event.name.replace(/\s+/g, '_')}_itinerary_${data.event.date}.pdf`;
  doc.save(fileName);
}

/**
 * Generates a shareable link for the itinerary
 */
export function generateShareableLink(eventId: string): string {
  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  return `${baseUrl}/itinerary/${eventId}`;
}

/**
 * Validates time overlap between performances
 */
export function hasTimeOverlap(
  p1: { start_time: string; end_time: string },
  p2: { start_time: string; end_time: string }
): boolean {
  const start1 = timeToMinutes(p1.start_time);
  const end1 = timeToMinutes(p1.end_time);
  const start2 = timeToMinutes(p2.start_time);
  const end2 = timeToMinutes(p2.end_time);

  // Handle midnight crossover
  const adjustedEnd1 = end1 < start1 ? end1 + 24 * 60 : end1;
  const adjustedEnd2 = end2 < start2 ? end2 + 24 * 60 : end2;

  // Check for overlap
  if (start1 < adjustedEnd1 && start2 < adjustedEnd2) {
    // Standard day case
    return start1 < adjustedEnd2 && start2 < adjustedEnd1;
  }
  
  return false;
}

/**
 * Converts time string to minutes since midnight
 */
function timeToMinutes(time: string): number {
  const [hours, minutes] = time.split(':').map(Number);
  return hours * 60 + minutes;
}